/**
 * Generate public/sitemap.xml from the indexing policy in src/app/lib/seo.tsx.
 *
 * Why this exists. The sitemap was hand-written, which made two problems
 * inevitable. It was a *second* source of truth for "which routes are public and
 * indexable" alongside `SEO_ROUTES.noindex`, so adding a public route meant
 * remembering to edit both and the two could silently disagree — the failure mode
 * being a live public page that never gets indexed, or an auth-gated page
 * advertised to crawlers. And `lastmod` was a literal date that went stale the
 * day after it was written, which is worse than omitting it.
 *
 * Deliberately a regex read of the route table rather than importing it. The
 * table lives in a .tsx module with JSX and TS types, so importing it from plain
 * Node would need a transpiler in the build path. What is needed here is two
 * fields per route, the shape is fixed and adjacent in the source, and a
 * mismatch fails loudly below rather than silently emitting a wrong sitemap.
 *
 * Run by `npm run build` before vite, so dist/ always carries a current file.
 */

import { readFileSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const SEO_SOURCE = resolve(here, "../src/app/lib/seo.tsx");
const OUT = resolve(here, "../public/sitemap.xml");
const ORIGIN = "https://digonto.ahbab.dev";

// How often each public route's content actually changes, and its relative
// weight. Not derivable from the route table, so it is declared here; a public
// route missing from this map fails the build rather than getting a silent
// default, because guessing wrong is an SEO decision made by accident.
const POLICY = {
  "/": { changefreq: "weekly", priority: "1.0" },
  "/destinations": { changefreq: "weekly", priority: "0.8" },
  "/ledger": { changefreq: "weekly", priority: "0.8" },
  "/security": { changefreq: "monthly", priority: "0.5" },
  "/about": { changefreq: "monthly", priority: "0.5" },
};

const source = readFileSync(SEO_SOURCE, "utf8");

// Each entry in SEO_ROUTES declares `path:` then, a few lines later, `noindex:`.
const entries = [...source.matchAll(/path:\s*"([^"]+)"[\s\S]{0,900}?noindex:\s*(true|false)/g)]
  .map(([, path, noindex]) => ({ path, indexable: noindex === "false" }));

if (entries.length === 0) {
  throw new Error(`generate-sitemap: parsed no routes from ${SEO_SOURCE}`);
}

const indexable = entries.filter((e) => e.indexable).map((e) => e.path);

const missing = indexable.filter((p) => !(p in POLICY));
if (missing.length > 0) {
  throw new Error(
    `generate-sitemap: ${missing.join(", ")} is indexable in SEO_ROUTES but has no ` +
      `changefreq/priority in scripts/generate-sitemap.mjs. Add it deliberately.`,
  );
}
const stale = Object.keys(POLICY).filter((p) => !indexable.includes(p));
if (stale.length > 0) {
  throw new Error(
    `generate-sitemap: ${stale.join(", ")} has a sitemap policy but is not indexable ` +
      `in SEO_ROUTES. Remove it, or set noindex: false.`,
  );
}

// Build date, not "now at request time": this is a static artefact and the day it
// was produced is the honest answer for when the content last changed.
const lastmod = new Date().toISOString().slice(0, 10);

const urls = indexable
  .map((path) => {
    const loc = `${ORIGIN}${path === "/" ? "/" : path}`;
    const { changefreq, priority } = POLICY[path];
    // Both languages live at one URL (the toggle is client-side), so each is its
    // own hreflang alternate with x-default pointing at the same place.
    return `  <url>
    <loc>${loc}</loc>
    <xhtml:link rel="alternate" hreflang="bn" href="${loc}" />
    <xhtml:link rel="alternate" hreflang="en" href="${loc}" />
    <xhtml:link rel="alternate" hreflang="x-default" href="${loc}" />
    <lastmod>${lastmod}</lastmod>
    <changefreq>${changefreq}</changefreq>
    <priority>${priority}</priority>
  </url>`;
  })
  .join("\n");

const gated = entries.filter((e) => !e.indexable).map((e) => e.path).join(", ");

writeFileSync(
  OUT,
  `<?xml version="1.0" encoding="UTF-8"?>
<!-- GENERATED by scripts/generate-sitemap.mjs from SEO_ROUTES in
     src/app/lib/seo.tsx. Do not edit by hand; edit the route table instead.
     Excluded as noindex: ${gated}
     See docs/seo.md. -->
<urlset
  xmlns="http://www.sitemaps.org/schemas/sitemap/0.9"
  xmlns:xhtml="http://www.w3.org/1999/xhtml"
>
${urls}
</urlset>
`,
  "utf8",
);

console.log(
  `sitemap.xml: ${indexable.length} indexable route(s) [${indexable.join(", ")}], lastmod ${lastmod}`,
);
