"""Lekhok (লেখক), the Statement Forensics agent.

A statement of purpose that contradicts the applicant's own documents is a
common and entirely avoidable refusal ground. It happens most often when a
consultancy writes the statement, because whoever wrote it never saw the
transcripts.

Lekhok does not write statements. It reports problems in one the student wrote
and suggests clearer phrasing for claims they already made truthfully. A
statement generated by a model is exactly the artefact admissions offices have
started screening for, and producing one would harm the student.
"""

from __future__ import annotations

import logging
from typing import Any

from app.agents.runtime import REFUSAL_NOTE, AgentCall, structured
from app.llm.router import ModelRouter, TaskKind

log = logging.getLogger(__name__)

SCHEMA = {
    "type": "object",
    "properties": {
        "findings": {
            "type": "array",
            "items": {
                "type": "object",
                "properties": {
                    "severity": {"type": "string", "enum": ["critical", "warning", "info"]},
                    "kind": {
                        "type": "string",
                        "enum": ["contradiction", "unsupported", "vague", "cliche", "missing"],
                    },
                    "excerpt": {"type": "string"},
                    "detail_en": {"type": "string"},
                    "detail_bn": {"type": "string"},
                    "suggestion_en": {"type": "string"},
                    "suggestion_bn": {"type": "string"},
                    "conflicts_document_kind": {"type": "string"},
                },
                "required": [
                    "severity", "kind", "excerpt",
                    "detail_en", "detail_bn", "suggestion_en", "suggestion_bn",
                ],
            },
        }
    },
    "required": ["findings"],
}

SYSTEM = (
    "You are Lekhok. You review a statement of purpose written by a Bangladeshi "
    "student and report problems. Categories: contradiction (conflicts with the "
    "student's own record), unsupported (a claim nothing in the record backs), "
    "vague (asserts nothing checkable), cliche (occupies space an officer is "
    "scanning), missing (a question the reader will have that the statement "
    "never answers). Quote the exact excerpt for each finding. Suggest clearer "
    "phrasing for claims the student already made. "
    "You must not write the statement, invent achievements, or add claims the "
    "student did not make. If asked to write it, refuse and explain that a "
    "statement written by someone else is the thing admissions offices screen "
    "for. Bangla must be natural. " + REFUSAL_NOTE
)


async def analyse_statement(
    *,
    body: str,
    documents: list[dict[str, Any]],
    router: ModelRouter,
) -> list[dict[str, Any]]:
    """Check a statement against the student's own record."""
    # Only metadata is sent, never document contents. Kind, dates, and the
    # institution are enough to detect a date or qualification contradiction.
    record = "\n".join(
        f"- kind={d.get('kind')} issued={d.get('issued_on')} "
        f"expires={d.get('expires_on')} name={d.get('original_name')}"
        for d in documents
    ) or "no documents uploaded"

    try:
        data = await structured(
            router,
            AgentCall(
                kind=TaskKind.AGENT_TOOL,
                system=SYSTEM,
                user=(
                    f"STUDENT RECORD (metadata only):\n{record}\n\n"
                    f"STATEMENT:\n{body}"
                ),
                schema=SCHEMA,
                contains_user_documents=True,
                thinking=True,
                max_tokens=3072,
            ),
        )
    except Exception as exc:  # noqa: BLE001
        log.warning("lekhok analysis failed: %s", exc)
        return []

    out: list[dict[str, Any]] = []
    for f in data.get("findings", []):
        if f.get("severity") not in ("critical", "warning", "info"):
            f["severity"] = "warning"
        if f.get("kind") not in ("contradiction", "unsupported", "vague", "cliche", "missing"):
            f["kind"] = "vague"
        out.append(f)
    return out
